### ISSUE TITLE
How do i build levigo under windows?

### ISSUE THREAD

**Issue by luckcolors** [jmhodges/levigo#31]
I succefully built this project : https://bitbucket.org/robertvazan/leveldb-windows (the only one that i can find to build levelDB under windows)
And i got the leveldb.lib
How i can use it to build levigo?
Thanks in advance if you help me :).

**Comment by jmhodges** [comment]
Sorry, I don't have any insight into Windows. The usual way you build cgo libraries (as documented in the README) should work.
